{% set version = "0.3.0" %}

package:
    name: pyepsg
    version: {{ version }}

source:
    fn: pyepsg-{{ version }}.tar.gz
    url: https://github.com/rhattersley/pyepsg/archive/v{{ version }}.tar.gz
    sha256: e9dc5566eb8fc0015e49d899721930d4d93eaa172712d560a93373b8a21dc3c2

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python
        - requests

test:
    imports:
        - pyepsg

about:
    home: https://pypi.python.org/pypi/pyepsg
    license: LGPL
    summary: Easy access to the EPSG database via http://epsg.io/

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
