{% set version = "0.3.2" %}

package:
  name: pyepsg
  version: {{ version }}

source:
  url: https://github.com/rhattersley/pyepsg/archive/v{{ version }}.tar.gz
  sha256: 2af92df0f398db458485b76d58ba8303202c93ed30ccd27c4c6463e90b4a79d2

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - pyepsg

about:
  home: https://pypi.python.org/pypi/pyepsg
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Easy access to the EPSG database via http://epsg.io/'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
