travis:
  secure:
    BINSTAR_TOKEN: i/8AL0FtvjG8rFyfbliTVHe7jN4wvgcAqZ2OS8vbqrEkrgGn8y357f3L5Y7X3GrVSv6TMslzUgjYN0Lev6A6sapagtISjQduv03WcJoU3sQkJoCutPK9Mal5QimvTrF3ntXvTQdk6UTV6NPzM2fHLbpQPJyCJCfnjZkFrl2tWMnbL91RszZUVcMeCLfR+K91EtlUQCzq0kNWyWB9yjnbTsm7CDT0V8tDDDXT/ATu1sZoxdsgahpLlsDFs9Is21OysETJWw2HG3xr8O98nyvbiV42RcdAIcMrodCqOvnTazZvEUB/Z/mXEy86qqIxtm0kN1QoEaTUYHmYbn6Ud1AFp4OQIo+hz9p9pGGWqD6sbH+11noJoVPwuTnwuoxx/64eItsQUizGGj6xK/4DS1JW/Ds6/WBQ/eMjsZJzn1QmOB4/d2s9ZEkn9wxZvbvt3pi0UbJk1Q/O+TZZaV+lR/YXnduV/wzLHFqWW6obIHKvubVs7ZF6hDWuQgJAqgE0ytcgaEieHO0/MXKddHgct6jFZIQYBVeGhVfMWSVZZVVARrh4BMq11nktrcijMXnsyE6qtNFsS9MXyPwRKr0th9GHiQFIagD2JLjdSCcC/TiFt1efPaUYX8QXeh/OP7TanqSfwXByQTtxv0PTvmSzGvMeT3pdX+/hmH/5MI2bcBWALY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
