travis:
  secure:
    BINSTAR_TOKEN: m0UU+fFnkbLEswuLH3al219R8nYse1dajjQkHy6OvV6c0V7UMuYAG6BJrJ26GUZNQqax/YEIRWFPMJw3a8NLAbbtQz9Mx1nIerl49nOu3PAtE/Tdt4FThaZ3he7J+1u4M5F1JMLFGLOcqqHKMHEZkrGv4GnwFU8KLI24kOmL2rE58PlC7tgmQhhpbZsZNyognQBwXbcK6AsnSHB3Yr7LvhMe0D3FjD8whvbpZn1FhZLO20bmnbzXL15J2CMUjA9/W0Bd3Q0H4txKoD+aREH+gw8qEyjdyC3pVrxjbVrf+nwmgkudDAQN1QmpOtjP+uiIrhpxt6hFvqW2/oYDeCof+vFXhqQCWX+sdv8A3oIg7bUdr2eEggUUzdJ3vb3Dg2+i0pvCKXxErqk1D8zO/63hVUWLb5tgF+MBrHsQhRbx/5CcOJ0HsmyHlraRHPa3HF3nZkBH/oMo+N/2OymN86QPIBxTPY4+OmSU7z47/jXkTVRhgpxg8hI7QCrXfOVwydO0uS53KEFKvc5FHg4OV5XCMffAh9S19mq1zatom9eNwsn1M8ntf3R+qGaq0PjJQermIomO8KxzDBYANkXErpb/l+y4mMpbjOC+DFyFJ8QIFlFxai/M7xrXyPbIDPZbVAGWO7k53ZniDfiEvORt9MbFwoK2wZeusv7P/rb+zvda+yo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
